// src/mockCyclones.js

export const mockHistoricalCyclones = [
  {
    id: "ARB-01-2023",
    name: "BIPARJOY",
    year: 2023,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryName: "Very Severe Cyclonic Storm",
    maxWindKmph: 165,
    minPressureHpa: 958,
    landfallLocation: "Naliya, Gujarat",
    durationDays: 13,
    primarySource: "IMD / RSMC New Delhi",
    satelliteTracked: "INSAT-3D / HURSAT",
    totalAdvisories: 48,
  },
  {
    id: "BOB-05-2020",
    name: "AMPHAN",
    year: 2020,
    basin: "Bay of Bengal",
    category: "SuCS",
    categoryName: "Super Cyclonic Storm",
    maxWindKmph: 240,
    minPressureHpa: 907,
    landfallLocation: "Bakkhali, West Bengal",
    durationDays: 6,
    primarySource: "IBTrACS / IMD",
    satelliteTracked: "INSAT-3DR / HURSAT-B1",
    totalAdvisories: 36,
  },
  {
    id: "BOB-02-2019",
    name: "FANI",
    year: 2019,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryName: "Extremely Severe Cyclonic Storm",
    maxWindKmph: 215,
    minPressureHpa: 932,
    landfallLocation: "Puri, Odisha",
    durationDays: 9,
    primarySource: "IBTrACS",
    satelliteTracked: "INSAT-3D",
    totalAdvisories: 42,
  },
  {
    id: "ARB-02-2021",
    name: "TAUKTAE",
    year: 2021,
    basin: "Arabian Sea",
    category: "ESCS",
    categoryName: "Extremely Severe Cyclonic Storm",
    maxWindKmph: 195,
    minPressureHpa: 950,
    landfallLocation: "Una, Gujarat",
    durationDays: 6,
    primarySource: "RSMC New Delhi",
    satelliteTracked: "MOSDAC / INSAT-3DR",
    totalAdvisories: 32,
  },
  {
    id: "BOB-07-2018",
    name: "GAJA",
    year: 2018,
    basin: "Bay of Bengal",
    category: "VSCS",
    categoryName: "Very Severe Cyclonic Storm",
    maxWindKmph: 140,
    minPressureHpa: 975,
    landfallLocation: "Nagapattinam, Tamil Nadu",
    durationDays: 8,
    primarySource: "IMD",
    satelliteTracked: "Digital Typhoon / HURSAT",
    totalAdvisories: 30,
  },
  {
    id: "BOB-04-2014",
    name: "HUDHUD",
    year: 2014,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryName: "Extremely Severe Cyclonic Storm",
    maxWindKmph: 185,
    minPressureHpa: 950,
    landfallLocation: "Visakhapatnam, Andhra Pradesh",
    durationDays: 7,
    primarySource: "IBTrACS / IMD",
    satelliteTracked: "INSAT-3D",
    totalAdvisories: 34,
  },
  {
    id: "BOB-01-2013",
    name: "PHAILIN",
    year: 2013,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryName: "Extremely Severe Cyclonic Storm",
    maxWindKmph: 215,
    minPressureHpa: 940,
    landfallLocation: "Gopalpur, Odisha",
    durationDays: 6,
    primarySource: "IBTrACS",
    satelliteTracked: "Kaggle Unified / HURSAT",
    totalAdvisories: 28,
  },
  {
    id: "ARB-01-2015",
    name: "CHAPALA",
    year: 2015,
    basin: "Arabian Sea",
    category: "ESCS",
    categoryName: "Extremely Severe Cyclonic Storm",
    maxWindKmph: 215,
    minPressureHpa: 940,
    landfallLocation: "Mukalla, Yemen",
    durationDays: 7,
    primarySource: "RSMC New Delhi / IBTrACS",
    satelliteTracked: "Digital Typhoon",
    totalAdvisories: 31,
  }
];