// src/mockSatelliteData.js

export const mockSatelliteFrames = [
  {
    id: "SAT-2026-001",
    cycloneName: "BIPARJOY-II",
    year: 2026,
    timestamp: "2026-08-25 18:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager TIR-1 (10.8µm)",
    channel: "TIR-1 (10.8µm)",
    category: "VSCS",
    resolution: "4 km",
    stormCenter: "18.4°N, 67.2°E",
    eyeVisibility: "Prominent Eye Structure",
    colorScale: "Enhanced BD-Curve",
    source: "MOSDAC / ISRO",
    imagePlaceholderBg: "from-slate-950 via-cyan-950 to-slate-900",
    description: "Deep convective eyewall with cold cloud-top temperatures below -78°C detected by INSAT-3DR TIR-1 channel over the East-Central Arabian Sea."
  },
  {
    id: "SAT-2026-002",
    cycloneName: "BIPARJOY-II",
    year: 2026,
    timestamp: "2026-08-25 18:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager WV (6.8µm)",
    channel: "Water Vapor (6.8µm)",
    category: "VSCS",
    resolution: "8 km",
    stormCenter: "18.4°N, 67.2°E",
    eyeVisibility: "Deep Upper Tropospheric Dry Slot",
    colorScale: "WV Dry/Moist Standard",
    source: "MOSDAC / ISRO",
    imagePlaceholderBg: "from-slate-950 via-teal-950 to-slate-900",
    description: "Mid-to-upper tropospheric moisture flux channeling into the western quadrant, confirming northward steering propagation."
  },
  {
    id: "SAT-2020-001",
    cycloneName: "AMPHAN",
    year: 2020,
    timestamp: "2020-05-18 06:00 UTC",
    satellite: "INSAT-3D",
    sensor: "Imager TIR-1 (10.8µm)",
    channel: "TIR-1 (10.8µm)",
    category: "SuCS",
    resolution: "4 km",
    stormCenter: "13.5°N, 86.3°E",
    eyeVisibility: "Symmetric Stadium Effect",
    colorScale: "Enhanced BD-Curve",
    source: "MOSDAC / ISRO",
    imagePlaceholderBg: "from-slate-950 via-purple-950 to-slate-900",
    description: "Super Cyclonic Storm stadium effect with central dense overcast temperatures dropping below -82°C over the Bay of Bengal."
  },
  {
    id: "SAT-2020-002",
    cycloneName: "AMPHAN",
    year: 2020,
    timestamp: "2020-05-18 12:00 UTC",
    satellite: "HURSAT-B1",
    sensor: "Gridded Radiometer (11.0µm)",
    channel: "Clean IR (11.0µm)",
    category: "SuCS",
    resolution: "8 km Gridded",
    stormCenter: "14.2°N, 86.3°E",
    eyeVisibility: "Compact Cold Core Eye",
    colorScale: "Dvorak IR Standard",
    source: "NOAA NCEI",
    imagePlaceholderBg: "from-slate-950 via-indigo-950 to-slate-900",
    description: "Calibrated 8km gridded infrared radiometry matrix centered on the storm vortex, standardized for intensity estimation."
  },
  {
    id: "SAT-2019-001",
    cycloneName: "FANI",
    year: 2019,
    timestamp: "2019-05-02 12:00 UTC",
    satellite: "INSAT-3D",
    sensor: "Imager TIR-1 (10.8µm)",
    channel: "TIR-1 (10.8µm)",
    category: "ESCS",
    resolution: "4 km",
    stormCenter: "16.5°N, 85.0°E",
    eyeVisibility: "Well-Defined Curved Band",
    colorScale: "Enhanced BD-Curve",
    source: "MOSDAC / ISRO",
    imagePlaceholderBg: "from-slate-950 via-rose-950 to-slate-900",
    description: "Extremely Severe Cyclonic Storm prior to Odisha landfall showing sharp eyewall definition and high spiral band symmetry."
  },
  {
    id: "SAT-2021-001",
    cycloneName: "TAUKTAE",
    year: 2021,
    timestamp: "2021-05-17 00:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager MIR (3.9µm)",
    channel: "Middle IR (3.9µm)",
    category: "ESCS",
    resolution: "4 km",
    stormCenter: "18.5°N, 71.5°E",
    eyeVisibility: "Nocturnal Core Heat Signature",
    colorScale: "MIR Hot-Spot Inversion",
    source: "MOSDAC / ISRO",
    imagePlaceholderBg: "from-slate-950 via-amber-950 to-slate-900",
    description: "Middle-infrared nocturnal frame isolating active deep convective bursting parallel to the Mumbai and Konkan coastline."
  },
  {
    id: "SAT-2023-001",
    cycloneName: "BIPARJOY",
    year: 2023,
    timestamp: "2023-06-11 06:00 UTC",
    satellite: "HURSAT-B1",
    sensor: "Gridded Radiometer (11.0µm)",
    channel: "Clean IR (11.0µm)",
    category: "ESCS",
    resolution: "8 km Gridded",
    stormCenter: "18.2°N, 67.7°E",
    eyeVisibility: "Intense Ragged Eye Structure",
    colorScale: "Dvorak IR Standard",
    source: "NOAA NCEI",
    imagePlaceholderBg: "from-slate-950 via-blue-950 to-slate-900",
    description: "Standardized storm-centered top-of-atmosphere tensor showing slow northward recurvature in the East-Central Arabian Sea."
  },
  {
    id: "SAT-2014-001",
    cycloneName: "HUDHUD",
    year: 2014,
    timestamp: "2014-10-12 00:00 UTC",
    satellite: "Digital Typhoon Archival",
    sensor: "Infrared Radiometer (10.8µm)",
    channel: "Infrared-1 (10.8µm)",
    category: "ESCS",
    resolution: "5 km",
    stormCenter: "17.4°N, 84.1°E",
    eyeVisibility: "Coincident Landfall Eye",
    colorScale: "Standard IR Thermal",
    source: "Kitamoto Lab (NII)",
    imagePlaceholderBg: "from-slate-950 via-emerald-950 to-slate-900",
    description: "Benchmark cross-basin archival frame capturing eyewall strike at Visakhapatnam, Andhra Pradesh."
  },
];