// src/mockData.js

export const mockCycloneDetail = {
  id: "ARB-01-2026",
  name: "BIPARJOY-II",
  year: 2026,
  basin: "Arabian Sea (North Indian Ocean)",
  status: "ACTIVE",
  currentCategory: "VSCS",
  categoryName: "Very Severe Cyclonic Storm",
  currentPosition: {
    lat: 18.4,
    lng: 67.2,
    timestamp: "2026-08-25T18:00:00Z",
  },
  currentWindKmph: 145,
  maxSustainedWindKmph: 155,
  currentPressureHpa: 968,
  minPressureHpa: 962,
  movement: {
    direction: "NNW",
    headingDeg: 335,
    speedKmph: 12,
  },
  aiTelemetry: {
    detection: {
      model: "YOLOv8-IR-Custom",
      confidence: 0.94,
      eyeStatus: "Well Defined",
      lastInference: "2026-08-25 18:15 UTC",
    },
    classification: {
      model: "Vision-Transformer-Dvorak",
      confidence: 0.91,
      estimatedTNo: "T4.5",
      classificationBasis: "INSAT-3DR TIR-1 (10.8µm)",
      lastInference: "2026-08-25 18:15 UTC",
    },
    prediction: {
      model: "ConvLSTM-NWP-Fusion",
      confidence: 0.88,
      leadTimeHours: 72,
      lastInference: "2026-08-25 18:20 UTC",
    },
  },
  landfall: {
    isLandfallExpected: true,
    location: "Near Jakhau Port, Gujarat Coast",
    coordinates: [23.2, 68.6],
    estimatedTime: "2026-08-27T14:00:00Z",
    windAtLandfallKmph: 125,
    categoryAtLandfall: "VSCS",
    confidence: "High (86%)",
  },
  observedTrack: [
    { lat: 14.2, lng: 66.0, windKmph: 55, pressureHpa: 1000, time: "2026-08-24 00:00 UTC" },
    { lat: 15.1, lng: 66.2, windKmph: 75, pressureHpa: 994, time: "2026-08-24 06:00 UTC" },
    { lat: 16.0, lng: 66.5, windKmph: 95, pressureHpa: 986, time: "2026-08-24 12:00 UTC" },
    { lat: 16.9, lng: 66.8, windKmph: 120, pressureHpa: 978, time: "2026-08-24 18:00 UTC" },
    { lat: 17.6, lng: 67.0, windKmph: 135, pressureHpa: 972, time: "2026-08-25 06:00 UTC" },
    { lat: 18.4, lng: 67.2, windKmph: 145, pressureHpa: 968, time: "2026-08-25 18:00 UTC" },
  ],
  predictedTrack: [
    { lat: 19.1, lng: 67.0, windKmph: 150, time: "2026-08-26 00:00 UTC" },
    { lat: 19.9, lng: 67.1, windKmph: 155, time: "2026-08-26 06:00 UTC" },
    { lat: 21.4, lng: 67.6, windKmph: 145, time: "2026-08-26 18:00 UTC" },
    { lat: 23.2, lng: 68.6, windKmph: 125, time: "2026-08-27 14:00 UTC" },
    { lat: 25.1, lng: 70.4, windKmph: 65, time: "2026-08-28 18:00 UTC" },
  ],
  forecastTimeline: [
    { horizon: "+06h", validTime: "2026-08-26 00:00 UTC", lat: 19.1, lng: 67.0, windKmph: 150, pressureHpa: 965, category: "VSCS", confidence: 0.92 },
    { horizon: "+12h", validTime: "2026-08-26 06:00 UTC", lat: 19.9, lng: 67.1, windKmph: 155, pressureHpa: 962, category: "VSCS", confidence: 0.89 },
    { horizon: "+24h", validTime: "2026-08-26 18:00 UTC", lat: 21.4, lng: 67.6, windKmph: 145, pressureHpa: 968, category: "VSCS", confidence: 0.84 },
    { horizon: "+48h", validTime: "2026-08-27 18:00 UTC", lat: 23.5, lng: 68.9, windKmph: 110, pressureHpa: 980, category: "SCS", confidence: 0.76 },
    { horizon: "+72h", validTime: "2026-08-28 18:00 UTC", lat: 25.1, lng: 70.4, windKmph: 65, pressureHpa: 994, category: "CS", confidence: 0.68 },
  ],
};

export const mockAlerts = [
  {
    id: "ALT-01",
    severity: "severe",
    region: "Gujarat Coastal Zone (Kutch, Saurashtra)",
    issuedAt: "2026-08-25 17:30 UTC",
    message: "Landfall warning: Heavy to very heavy precipitation accompanied by storm surge expected within 48 hours.",
  },
  {
    id: "ALT-02",
    severity: "moderate",
    region: "Maharashtra Coast",
    issuedAt: "2026-08-25 16:00 UTC",
    message: "Rough sea conditions. Fishermen are advised not to venture into deep North Arabian Sea waters.",
  },
  {
    id: "ALT-03",
    severity: "watch",
    region: "Southwest Rajasthan",
    issuedAt: "2026-08-25 12:00 UTC",
    message: "Post-landfall depression tracking towards interior districts with localized flooding potential.",
  },
];

// Added missing historical catalog export
export const mockHistoricalCyclones = [
  {
    id: "ARB-01-2023",
    name: "BIPARJOY",
    year: 2023,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryLabel: "VSCS (Very Severe)",
    peakWindKmph: 165,
    minPressureHpa: 958,
    landfallLocation: "Naliya, Gujarat",
    source: "IMD / RSMC New Delhi",
  },
  {
    id: "BOB-05-2020",
    name: "AMPHAN",
    year: 2020,
    basin: "Bay of Bengal",
    category: "SuCS",
    categoryLabel: "SuCS (Super)",
    peakWindKmph: 240,
    minPressureHpa: 907,
    landfallLocation: "Bakkhali, West Bengal",
    source: "IBTrACS / IMD",
  },
  {
    id: "BOB-02-2019",
    name: "FANI",
    year: 2019,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS (Extremely)",
    peakWindKmph: 215,
    minPressureHpa: 932,
    landfallLocation: "Puri, Odisha",
    source: "IBTrACS",
  },
  {
    id: "ARB-02-2021",
    name: "TAUKTAE",
    year: 2021,
    basin: "Arabian Sea",
    category: "ESCS",
    categoryLabel: "ESCS (Extremely)",
    peakWindKmph: 195,
    minPressureHpa: 950,
    landfallLocation: "Una, Gujarat",
    source: "RSMC New Delhi",
  },
  {
    id: "BOB-07-2018",
    name: "GAJA",
    year: 2018,
    basin: "Bay of Bengal",
    category: "VSCS",
    categoryLabel: "VSCS (Very Severe)",
    peakWindKmph: 140,
    minPressureHpa: 975,
    landfallLocation: "Nagapattinam, Tamil Nadu",
    source: "IMD",
  },
  {
    id: "BOB-04-2014",
    name: "HUDHUD",
    year: 2014,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS (Extremely)",
    peakWindKmph: 185,
    minPressureHpa: 950,
    landfallLocation: "Visakhapatnam, Andhra Pradesh",
    source: "IBTrACS / IMD",
  },
  {
    id: "BOB-01-2013",
    name: "PHAILIN",
    year: 2013,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS (Extremely)",
    peakWindKmph: 215,
    minPressureHpa: 940,
    landfallLocation: "Gopalpur, Odisha",
    source: "IBTrACS",
  },
  {
    id: "ARB-01-2015",
    name: "CHAPALA",
    year: 2015,
    basin: "Arabian Sea",
    category: "ESCS",
    categoryLabel: "ESCS (Extremely)",
    peakWindKmph: 215,
    minPressureHpa: 940,
    landfallLocation: "Mukalla, Yemen",
    source: "RSMC New Delhi / IBTrACS",
  },
];
// Append to src/mockData.js

export const mockDataSources = [
  {
    id: "ibtracs",
    name: "IBTrACS",
    fullName: "International Best Track Archive for Climate Stewardship",
    organization: "NOAA NCEI",
    basinCoverage: "Global / North Indian Ocean (NIO)",
    format: "NetCDF4 / CSV",
    temporalResolution: "3-Hourly & 6-Hourly Synoptic Fixes",
    status: "Configured (Ground Truth)",
    statusType: "online",
    records: "12,480 fixes (NIO Basin)",
    lastSync: "2026-08-15 UTC",
    description: "Primary ground-truth historical benchmark standardizing storm center coordinates, minimum central pressure, and maximum sustained wind speeds across international agencies.",
    citation: "Knapp et al., NOAA National Centers for Environmental Information.",
  },
  {
    id: "hursat",
    name: "HURSAT-B1",
    fullName: "Hurricane Satellite Geostationary Radiometry",
    organization: "NOAA NCEI",
    basinCoverage: "North Indian Ocean, Western Pacific, Atlantic",
    format: "NetCDF4 (Gridded Tensors)",
    temporalResolution: "3-Hourly (8 km Spatial Grid)",
    status: "Configured (Image Archive)",
    statusType: "online",
    records: "8,920 Storm-Centered Crops",
    lastSync: "2026-07-22 UTC",
    description: "Calibrated geostationary infrared brightness temperature (TIR-1) matrices centered on storm eyes, optimized for Vision Transformer and CNN intensity classification training.",
    citation: "Knapp, K. R., NOAA NCEI Satellite Data Archive.",
  },
  {
    id: "mosdac",
    name: "MOSDAC",
    fullName: "Meteorological & Oceanographic Satellite Data Archival Centre",
    organization: "ISRO / Space Applications Centre",
    basinCoverage: "Indian Subcontinent & Surrounding Seas",
    format: "HDF5 / GeoTIFF",
    temporalResolution: "Half-Hourly (4 km Native Grid)",
    status: "Simulation Stream Active",
    statusType: "online",
    records: "Real-Time Ingestion Stream",
    lastSync: "2026-08-25 18:00 UTC",
    description: "High-cadence thermal infrared (10.8µm) and water vapor channels from INSAT-3D and INSAT-3DR geostationary orbiters, feeding real-time vortex center detection.",
    citation: "Space Applications Centre (SAC), Indian Space Research Organisation (ISRO).",
  },
  {
    id: "rsmc",
    name: "RSMC New Delhi",
    fullName: "Regional Specialized Meteorological Centre for Tropical Cyclones",
    organization: "India Meteorological Department (IMD)",
    basinCoverage: "North Indian Ocean (Bay of Bengal & Arabian Sea)",
    format: "Synoptic Bulletins / Track JSON",
    temporalResolution: "Operational Advisories (3-Hourly During Active Storms)",
    status: "Sync Active",
    statusType: "online",
    records: "Operational Bulletin Archive",
    lastSync: "2026-08-25 18:00 UTC",
    description: "Authoritative meteorological bulletins, cone of uncertainty boundaries, storm surge projections, and coastal landfall warnings covering the Indian coastline.",
    citation: "Cyclone Warning Division, India Meteorological Department, New Delhi.",
  },
  {
    id: "typhoon",
    name: "Digital Typhoon",
    fullName: "National Institute of Informatics Geostationary Archive",
    organization: "Kitamoto Laboratory, NII Japan",
    format: "TAR / PNG / Track Metadata",
    basinCoverage: "Western North Pacific & NIO Cross-Validation",
    temporalResolution: "Hourly Storm-Centered Crops",
    status: "Supplementary (Standby)",
    statusType: "standby",
    records: "52,400 Benchmark Crops",
    lastSync: "2026-06-10 UTC",
    description: "Secondary image catalog used for cross-basin transfer learning, feature representation pre-training, and validating model robustness across different ocean domains.",
    citation: "Kitamoto Asanobu, National Institute of Informatics (NII).",
  },
  {
    id: "kaggle",
    name: "Kaggle Cyclone Repositories",
    fullName: "Curated Tropical Cyclone Satellite Benchmark Datasets",
    organization: "Open Data Community",
    basinCoverage: "Multi-Basin Pre-Processed Collections",
    format: "NumPy (.npy) / TFRecord / CSV",
    temporalResolution: "Standardized Static Benchmark Splits",
    status: "Local Prototyping Mode",
    statusType: "standby",
    records: "4,200 Pre-Processed Samples",
    lastSync: "2026-05-18 UTC",
    description: "Standardized 512x512 normalized tensor crops used for rapid prototyping, CI/CD model verification, and baseline inference pipeline benchmarking.",
    citation: "Curated satellite benchmark open data repositories.",
  },
];
// Append to src/mockData.js

export const mockDatasetRecords = [
  {
    stormId: "ARB-01-2026",
    stormName: "BIPARJOY-II",
    timestamp: "2026-08-25 18:00 UTC",
    lat: 18.4,
    lng: 67.2,
    windKmph: 145,
    pressureHpa: 968,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryLabel: "VSCS",
    source: "RSMC IMD / MOSDAC",
  },
  {
    stormId: "ARB-01-2026",
    stormName: "BIPARJOY-II",
    timestamp: "2026-08-25 12:00 UTC",
    lat: 17.6,
    lng: 67.0,
    windKmph: 135,
    pressureHpa: 972,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryLabel: "VSCS",
    source: "RSMC IMD / MOSDAC",
  },
  {
    stormId: "ARB-01-2026",
    stormName: "BIPARJOY-II",
    timestamp: "2026-08-25 06:00 UTC",
    lat: 16.9,
    lng: 66.8,
    windKmph: 120,
    pressureHpa: 978,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryLabel: "VSCS",
    source: "RSMC IMD / MOSDAC",
  },
  {
    stormId: "ARB-01-2026",
    stormName: "BIPARJOY-II",
    timestamp: "2026-08-24 18:00 UTC",
    lat: 16.0,
    lng: 66.5,
    windKmph: 95,
    pressureHpa: 986,
    basin: "Arabian Sea",
    category: "SCS",
    categoryLabel: "SCS",
    source: "RSMC IMD / MOSDAC",
  },
  {
    stormId: "ARB-01-2023",
    stormName: "BIPARJOY",
    timestamp: "2023-06-15 12:00 UTC",
    lat: 23.2,
    lng: 68.6,
    windKmph: 165,
    pressureHpa: 958,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryLabel: "VSCS",
    source: "IBTrACS / IMD",
  },
  {
    stormId: "ARB-01-2023",
    stormName: "BIPARJOY",
    timestamp: "2023-06-14 18:00 UTC",
    lat: 21.8,
    lng: 67.9,
    windKmph: 155,
    pressureHpa: 964,
    basin: "Arabian Sea",
    category: "VSCS",
    categoryLabel: "VSCS",
    source: "IBTrACS / IMD",
  },
  {
    stormId: "BOB-05-2020",
    stormName: "AMPHAN",
    timestamp: "2020-05-18 18:00 UTC",
    lat: 16.5,
    lng: 86.8,
    windKmph: 240,
    pressureHpa: 907,
    basin: "Bay of Bengal",
    category: "SuCS",
    categoryLabel: "SuCS",
    source: "IBTrACS / IMD",
  },
  {
    stormId: "BOB-05-2020",
    stormName: "AMPHAN",
    timestamp: "2020-05-17 12:00 UTC",
    lat: 13.2,
    lng: 86.3,
    windKmph: 195,
    pressureHpa: 935,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS",
    source: "IBTrACS / IMD",
  },
  {
    stormId: "BOB-02-2019",
    stormName: "FANI",
    timestamp: "2019-05-02 18:00 UTC",
    lat: 18.2,
    lng: 85.4,
    windKmph: 215,
    pressureHpa: 932,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS",
    source: "IBTrACS",
  },
  {
    stormId: "BOB-02-2019",
    stormName: "FANI",
    timestamp: "2019-05-01 12:00 UTC",
    lat: 15.0,
    lng: 84.8,
    windKmph: 185,
    pressureHpa: 950,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS",
    source: "IBTrACS",
  },
  {
    stormId: "ARB-02-2021",
    stormName: "TAUKTAE",
    timestamp: "2021-05-17 18:00 UTC",
    lat: 20.8,
    lng: 71.1,
    windKmph: 195,
    pressureHpa: 950,
    basin: "Arabian Sea",
    category: "ESCS",
    categoryLabel: "ESCS",
    source: "RSMC New Delhi",
  },
  {
    stormId: "BOB-07-2018",
    stormName: "GAJA",
    timestamp: "2018-11-15 18:00 UTC",
    lat: 10.4,
    lng: 79.8,
    windKmph: 140,
    pressureHpa: 975,
    basin: "Bay of Bengal",
    category: "VSCS",
    categoryLabel: "VSCS",
    source: "IMD / RSMC",
  },
  {
    stormId: "BOB-04-2014",
    stormName: "HUDHUD",
    timestamp: "2014-10-12 06:00 UTC",
    lat: 17.7,
    lng: 83.3,
    windKmph: 185,
    pressureHpa: 950,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS",
    source: "IBTrACS / IMD",
  },
  {
    stormId: "BOB-01-2013",
    stormName: "PHAILIN",
    timestamp: "2013-10-12 12:00 UTC",
    lat: 19.1,
    lng: 85.0,
    windKmph: 215,
    pressureHpa: 940,
    basin: "Bay of Bengal",
    category: "ESCS",
    categoryLabel: "ESCS",
    source: "IBTrACS",
  },
];
// Append to src/mockData.js

export const mockSatelliteFrames = [
  {
    id: "SAT-2026-001",
    cycloneName: "BIPARJOY-II",
    year: 2026,
    timestamp: "2026-08-25 18:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager TIR-1 (10.8µm)",
    channelType: "Thermal IR",
    resolution: "4 km",
    minBrightnessTempK: 192.4,
    centerCoord: [18.4, 67.2],
    enhancement: "BD-Curve Enhanced",
    dvorakTNo: "T4.5",
    source: "ISRO MOSDAC HDF5",
    description: "Well-defined eye pattern surrounded by intense eyewall convection over the North-East Arabian Sea.",
  },
  {
    id: "SAT-2026-002",
    cycloneName: "BIPARJOY-II",
    year: 2026,
    timestamp: "2026-08-25 12:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager WV (6.9µm)",
    channelType: "Water Vapor",
    resolution: "8 km",
    minBrightnessTempK: 215.1,
    centerCoord: [17.6, 67.0],
    enhancement: "Upper-Tropospheric Moisture",
    dvorakTNo: "T4.5",
    source: "ISRO MOSDAC HDF5",
    description: "Deep tropospheric dry slot intrusion along the western quadrant steering the vortex northward.",
  },
  {
    id: "SAT-2023-001",
    cycloneName: "BIPARJOY",
    year: 2023,
    timestamp: "2023-06-14 18:00 UTC",
    satellite: "INSAT-3D",
    sensor: "Imager TIR-1 (10.8µm)",
    channelType: "Thermal IR",
    resolution: "4 km",
    minBrightnessTempK: 188.6,
    centerCoord: [21.8, 67.9],
    enhancement: "BD-Curve Enhanced",
    dvorakTNo: "T5.0",
    source: "ISRO MOSDAC",
    description: "Symmetric cold cloud ring with CDO temperature below -80°C prior to Gujarat coastline strike.",
  },
  {
    id: "SAT-2020-001",
    cycloneName: "AMPHAN",
    year: 2020,
    timestamp: "2020-05-18 18:00 UTC",
    satellite: "HURSAT-B1",
    sensor: "Gridded Radiometer B1",
    channelType: "Thermal IR",
    resolution: "8 km",
    minBrightnessTempK: 181.2,
    centerCoord: [16.5, 86.8],
    enhancement: "Standard Thermal Grayscale",
    dvorakTNo: "T6.5",
    source: "NOAA NCEI NetCDF",
    description: "Super Cyclonic Storm stadium effect with extreme compact inner eye and deep convective banding.",
  },
  {
    id: "SAT-2020-002",
    cycloneName: "AMPHAN",
    year: 2020,
    timestamp: "2020-05-17 12:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager VIS (0.65µm)",
    channelType: "Visible",
    resolution: "1 km",
    minBrightnessTempK: null,
    centerCoord: [13.2, 86.3],
    enhancement: "High-Resolution Reflectance",
    dvorakTNo: "T5.5",
    source: "ISRO MOSDAC",
    description: "Daytime visible channel snapshot capturing spiraling feeder bands into the central vortex.",
  },
  {
    id: "SAT-2019-001",
    cycloneName: "FANI",
    year: 2019,
    timestamp: "2019-05-02 18:00 UTC",
    satellite: "HURSAT-B1",
    sensor: "Gridded Radiometer B1",
    channelType: "Thermal IR",
    resolution: "8 km",
    minBrightnessTempK: 186.0,
    centerCoord: [18.2, 85.4],
    enhancement: "BD-Curve Enhanced",
    dvorakTNo: "T6.0",
    source: "NOAA NCEI NetCDF",
    description: "Extremely Severe Cyclonic Storm showcasing distinct circular eye approaching Puri, Odisha.",
  },
  {
    id: "SAT-2021-001",
    cycloneName: "TAUKTAE",
    year: 2021,
    timestamp: "2021-05-17 12:00 UTC",
    satellite: "INSAT-3DR",
    sensor: "Imager TIR-1 (10.8µm)",
    channelType: "Thermal IR",
    resolution: "4 km",
    minBrightnessTempK: 190.4,
    centerCoord: [19.8, 71.0],
    enhancement: "BD-Curve Enhanced",
    dvorakTNo: "T5.0",
    source: "ISRO MOSDAC",
    description: "Intense convective burst over the eastern eyewall tracking parallel to the Maharashtra-Gujarat coast.",
  },
  {
    id: "SAT-2018-001",
    cycloneName: "GAJA",
    year: 2018,
    timestamp: "2018-11-15 12:00 UTC",
    satellite: "INSAT-3D",
    sensor: "Imager WV (6.9µm)",
    channelType: "Water Vapor",
    resolution: "8 km",
    minBrightnessTempK: 219.0,
    centerCoord: [10.8, 80.4],
    enhancement: "Water Vapor Gradient",
    dvorakTNo: "T4.0",
    source: "ISRO MOSDAC",
    description: "Moderate shear environment evident via asymmetric mid-tropospheric moisture transport.",
  },
];
// Append to src/mockData.js

export const mockDataQualityReport = {
  summary: {
    totalRecordsAudited: 42890,
    validityRate: 98.6,
    missingValueCount: 142,
    duplicateCount: 18,
    invalidCoordCount: 9,
    sourceConflictCount: 24,
    corruptFileCount: 3,
    lastAuditTimestamp: "2026-08-25 18:30 UTC",
  },
  missingFields: [
    {
      field: "Central Pressure (hPa)",
      affectedSources: "HURSAT-B1, Kaggle Repos",
      count: 86,
      impact: "Moderate",
      remediation: "Dvorak P-W Empirical Estimation",
    },
    {
      field: "Translation Speed (km/h)",
      affectedSources: "IBTrACS Early Records (pre-2000)",
      count: 34,
      impact: "Low",
      remediation: "Great-Circle Distance Interpolation",
    },
    {
      field: "Eyewall Max Temperature (TIR-1)",
      affectedSources: "MOSDAC HDF5 (Overcast Gaps)",
      count: 14,
      impact: "High",
      remediation: "Cloud-Mask Linear Imputation",
    },
    {
      field: "Scatterometer Wind Vectors",
      affectedSources: "ASCAT / Oceansat Swath Gaps",
      count: 8,
      impact: "Moderate",
      remediation: "NWP Reanalysis Substitution",
    },
  ],
  coordinateAnomalies: [
    {
      stormId: "BOB-02-2019",
      fixTime: "2019-05-01 06:00 UTC",
      reportedCoord: [14.8, 98.4],
      issue: "Inverted Longitude Offset (East of Malay Peninsula)",
      severity: "Critical",
      status: "Auto-Corrected to 89.4°E",
    },
    {
      stormId: "ARB-01-2015",
      fixTime: "2015-10-28 18:00 UTC",
      reportedCoord: [13.2, 42.1],
      issue: "Inland Jump (Yemen Highlands inland by 180 km)",
      severity: "Moderate",
      status: "Spline Smoothed",
    },
    {
      stormId: "BOB-04-2014",
      fixTime: "2014-10-10 12:00 UTC",
      reportedCoord: [0.0, 0.0],
      issue: "Null Island Coordinate Reset",
      severity: "Critical",
      status: "Discarded Fix",
    },
  ],
  sourceConflicts: [
    {
      stormName: "BIPARJOY (2023)",
      timestamp: "2023-06-12 12:00 UTC",
      sourceA: "IMD RSMC (165 km/h)",
      sourceB: "JTWC / IBTrACS (185 km/h)",
      delta: "+20 km/h (1-min vs 3-min average)",
      resolution: "IMD Standard Retained",
    },
    {
      stormName: "TAUKTAE (2021)",
      timestamp: "2021-05-17 06:00 UTC",
      sourceA: "IMD RSMC (950 hPa)",
      sourceB: "HURSAT-B1 Est. (958 hPa)",
      delta: "-8 hPa Central Deficit",
      resolution: "Harmonized Ensemble Mean",
    },
    {
      stormName: "FANI (2019)",
      timestamp: "2019-05-02 18:00 UTC",
      sourceA: "MOSDAC TIR-1 (186 K)",
      sourceB: "NOAA HURSAT (189 K)",
      delta: "+3 K Radiometric Offset",
      resolution: "Sensor Cross-Calibration Applied",
    },
  ],
};
