// src/mockDataQuality.js

export const mockQualityMetrics = {
  overallHealthScore: 94.2,
  totalRecordsAudited: 48920,
  flaggedIssuesCount: 284,
  lastAuditRun: "2026-08-25 21:30 UTC",
  pipelineStatus: "OPERATIONAL",
  
  // High-level categorical counts
  anomalySummary: {
    missingValues: 112,
    duplicateRecords: 38,
    invalidCoordinates: 24,
    unmatchedStorms: 18,
    brokenFiles: 42,
    sourceConflicts: 50,
  },

  // Per-source audit scorecard
  sourceHealth: [
    {
      source: "IBTrACS",
      provider: "NOAA NCEI",
      healthScore: 98.4,
      status: "PASS",
      records: 18450,
      missingPct: "0.4%",
      duplicatePct: "0.0%",
      geoAnomalies: 2,
    },
    {
      source: "HURSAT-B1",
      provider: "NOAA NCEI",
      healthScore: 96.1,
      status: "PASS",
      records: 12400,
      missingPct: "1.2%",
      duplicatePct: "0.1%",
      geoAnomalies: 0,
    },
    {
      source: "MOSDAC (INSAT-3D/3DR)",
      provider: "ISRO / SAC",
      healthScore: 91.8,
      status: "WARNING",
      records: 9820,
      missingPct: "3.1%",
      duplicatePct: "0.4%",
      geoAnomalies: 11,
    },
    {
      source: "RSMC New Delhi",
      provider: "IMD",
      healthScore: 95.0,
      status: "PASS",
      records: 3150,
      missingPct: "0.8%",
      duplicatePct: "0.0%",
      geoAnomalies: 3,
    },
    {
      source: "Digital Typhoon",
      provider: "Kitamoto Lab",
      healthScore: 93.6,
      status: "PASS",
      records: 3600,
      missingPct: "2.0%",
      duplicatePct: "0.2%",
      geoAnomalies: 5,
    },
    {
      source: "Kaggle Unified",
      provider: "Benchmark Archive",
      healthScore: 88.5,
      status: "WARNING",
      records: 1500,
      missingPct: "4.8%",
      duplicatePct: "1.1%",
      geoAnomalies: 3,
    },
  ],

  // Specific flagged integrity incidents
  recentAnomalies: [
    {
      id: "ERR-8901",
      stormId: "ARB-01-2023",
      source: "MOSDAC",
      issueType: "Broken File / Corrupted Swath",
      description: "HDF5 packet truncated at line 412. Brightness temperature channel TIR-1 NaN grid detected.",
      severity: "High",
      timestamp: "2026-08-25 19:15 UTC",
      resolution: "Frame auto-quarantined; fallback to HURSAT-B1 tensor.",
    },
    {
      id: "ERR-8902",
      stormId: "BOB-05-2020",
      source: "RSMC New Delhi vs IBTrACS",
      issueType: "Source Conflict (Intensity Discrepancy)",
      description: "MSW mismatch: RSMC reported 130 kts (3-min sustained) vs IBTrACS recorded 140 kts (1-min sustained).",
      severity: "Medium",
      timestamp: "2026-08-25 18:40 UTC",
      resolution: "Standardized via WMO conversion factor (0.88 multiplier applied).",
    },
    {
      id: "ERR-8903",
      stormId: "ARB-02-2021",
      source: "Kaggle Unified",
      issueType: "Duplicate Record",
      description: "Identical spatiotemporal fix timestamp (2021-05-16 12:00 UTC) entered twice with varying rounding precision.",
      severity: "Low",
      timestamp: "2026-08-25 16:10 UTC",
      resolution: "Deduplicated via timestamp primary key constraint.",
    },
    {
      id: "ERR-8904",
      stormId: "BOB-02-2019",
      source: "MOSDAC",
      issueType: "Invalid Coordinates (Land Bounding)",
      description: "Initial cyclogenesis coordinate logged at 19.5°N, 73.1°E (Inland fix prior to offshore confirmation).",
      severity: "Medium",
      timestamp: "2026-08-25 14:22 UTC",
      resolution: "Corrected via Kalman smoothed trajectory interpolation.",
    },
    {
      id: "ERR-8905",
      stormId: "UNKNOWN-2017",
      source: "Digital Typhoon",
      issueType: "Unmatched Storm ID",
      description: "Deep Depression advisory lack WMO/RSMC standard identifier mapping.",
      severity: "Low",
      timestamp: "2026-08-25 11:05 UTC",
      resolution: "Assigned provisional ID `ARB-TEMP-2017-04`.",
    },
  ]
};