// src/mockDataSources.js

export const mockDataSources = [
  {
    id: "SRC-IBTRACS",
    name: "IBTrACS",
    fullName: "International Best Track Archive for Climate Stewardship",
    organization: "NOAA NCEI",
    datasetType: "Historical Cyclone Best Tracks (Global)",
    formats: ["CSV", "NetCDF", "Shapefile"],
    coverage: "Global (1848 – Present)",
    updateFrequency: "Monthly / Post-Season",
    status: "STANDBY",
    connectionType: "REST / HTTP Direct Archive",
    recordCount: "13,500+ Storms",
    primaryVariables: ["Latitude", "Longitude", "Max Sustained Wind", "Min Pressure", "Nature of Storm"],
    documentationUrl: "https://www.ncei.noaa.gov/products/international-best-track-archive",
    badgeColor: "border-blue-500/50 text-blue-300 bg-blue-950/40",
    description: "The official global repository synthesizing tropical cyclone track data from all Regional Specialized Meteorological Centres (RSMCs) worldwide.",
  },
  {
    id: "SRC-HURSAT",
    name: "HURSAT-B1",
    fullName: "Hurricane Satellite B1 Gridded Dataset",
    organization: "NOAA NCEI",
    datasetType: "Calibrated Geostationary IR Satellite Imagery",
    formats: ["NetCDF-4", "GeoTIFF"],
    coverage: "Global Tropical Basins (1978 – Present)",
    updateFrequency: "Quarterly",
    status: "STANDBY",
    connectionType: "NOAA S3 Open Data / HTTP",
    recordCount: "450,000+ Image Grids",
    primaryVariables: ["TIR (11µm)", "Water Vapor (6.7µm)", "Visible Albedo"],
    documentationUrl: "https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00842",
    badgeColor: "border-cyan-500/50 text-cyan-300 bg-cyan-950/40",
    description: "High-resolution storm-centered 3-hourly calibrated infrared and water vapor imagery grids extracted from international geostationary satellites.",
  },
  {
    id: "SRC-MOSDAC",
    name: "MOSDAC",
    fullName: "Meteorological and Oceanographic Satellite Data Archival Centre",
    organization: "ISRO / SAC Ahmedabad",
    datasetType: "INSAT-3D / INSAT-3DR Geostationary Payloads",
    formats: ["HDF5", "GeoTIFF", "PNG Quicklook"],
    coverage: "North Indian Ocean (Arabian Sea & Bay of Bengal)",
    updateFrequency: "Near Real-Time (15–30 min intervals)",
    status: "SIMULATED",
    connectionType: "MOSDAC Open Access API / FTP",
    recordCount: "128,000+ Swaths",
    primaryVariables: ["TIR-1 (10.8µm)", "MIR (3.9µm)", "WV (6.8µm)", "Scatterometer Surface Winds"],
    documentationUrl: "https://www.mosdac.gov.in",
    badgeColor: "border-emerald-500/50 text-emerald-300 bg-emerald-950/40",
    description: "ISRO's primary earth observation portal providing near-real-time multi-spectral radiometer and sounder acquisitions over the Indian subcontinent.",
  },
  {
    id: "SRC-RSMC",
    name: "RSMC New Delhi",
    fullName: "Regional Specialized Meteorological Centre for Tropical Cyclones",
    organization: "IMD (India Meteorological Department)",
    datasetType: "Operational Tropical Weather Outlooks & Best Tracks",
    formats: ["PDF Bulletins", "XML/JSON Feeds", "ASCII Text"],
    coverage: "North Indian Ocean (Bay of Bengal & Arabian Sea)",
    updateFrequency: "3-Hourly (During Active Cyclones)",
    status: "STANDBY",
    connectionType: "RSMC Bulletin Scraper / Open GeoJSON API",
    recordCount: "1,200+ Advisories",
    primaryVariables: ["Estimated Central Pressure", "MSW (3-min average)", "Landfall Forecast", "Sea State Warnings"],
    documentationUrl: "https://rsmcnewdelhi.imd.gov.in",
    badgeColor: "border-amber-500/50 text-amber-300 bg-amber-950/40",
    description: "The apex WMO-designated regional authority responsible for issuing tropical cyclone advisories, classifications, and track forecasts in the North Indian Ocean basin.",
  },
  {
    id: "SRC-DIGITAL-TYPHOON",
    name: "Digital Typhoon",
    fullName: "National Institute of Informatics Typhoon & Cyclone Archive",
    organization: "Kitamoto Laboratory (NII Japan)",
    datasetType: "Geostationary Imagery Sequences & Track Logs",
    formats: ["JPEG/PNG Sequence", "CSV", "TAR Grids"],
    coverage: "Western Pacific & Regional Oceanic Basins",
    updateFrequency: "Hourly (Archival)",
    status: "STANDBY",
    connectionType: "HTTP Archive Sync",
    recordCount: "180,000+ Labeled Frames",
    primaryVariables: ["Standardized Center-Cropped IR", "Dvorak T-Number Labels", "Minimum Pressure"],
    documentationUrl: "http://agora.ex.nii.ac.jp/digital-typhoon/",
    badgeColor: "border-purple-500/50 text-purple-300 bg-purple-950/40",
    description: "Standardized storm-centered satellite imagery repository with ground-truth intensity labels used for training classification models.",
  },
  {
    id: "SRC-KAGGLE-UNIFIED",
    name: "Kaggle Tropical Cyclone Datasets",
    fullName: "Community Curated Multi-Sensor Tropical Storm Benchmarks",
    organization: "Supplementary ML Benchmark Archive",
    datasetType: "Tabular & Standardized Satellite Tensors",
    formats: ["NumPy .npy", "Parquet", "CSV"],
    coverage: "Global Historical Benchmarks",
    updateFrequency: "Static / Benchmark Revisions",
    status: "STANDBY",
    connectionType: "Kaggle API / Direct Storage Ingestion",
    recordCount: "65,000+ Extracted Samples",
    primaryVariables: ["Pre-cropped 512x512 IR Tensors", "Wind Speed Radii", "Temporal Deltas"],
    documentationUrl: "https://www.kaggle.com",
    badgeColor: "border-slate-500/50 text-slate-300 bg-slate-900/40",
    description: "Pre-cleaned, normalized tensor arrays and tabular parameters used for baseline convolutional and recurrent sequence model validation.",
  }
];